[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = [
  "dotnet restore",
  "dotnet build -c Release"
]

[phases.build]
cmds = [
  "dotnet publish -c Release -o /app/publish"
]

[start]
cmd = "dotnet /app/publish/Backend.dll"

